[package]
name = "echo-server"
version = "0.1.0"
authors = ["Carlos Valiente <carlos@pepelabs.net>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
tokio = { "version" = "0.2.11", features = ["full"] }
